apiVersion: v1
kind: Pod
metadata:
  name: ci-awscli-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: awscli
      image: mesosphere/aws-cli:1.14.5
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
