apiVersion: v1
kind: Pod
metadata:
  name: ci-cypress-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: cypress
      image: cypress/base:13.6.0
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 2000m
          memory: 1024Mi
