apiVersion: v1
kind: Pod
metadata:
  name: ci-generic-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: jnlp
      image: jenkins/jnlp-slave:4.0.1-1-alpine
      command:
        - cat
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
      tty: true
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
