apiVersion: v1
kind: Pod
metadata:
  name: ci-git-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: git
      image: alpine/git:v2.24.1
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
