apiVersion: v1
kind: Pod
metadata:
  name: ci-kaniko-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug-v0.23.0
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
