apiVersion: v1
kind: Pod
metadata:
  name: ci-kubectl-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: kubectl
      image: boxboat/kubectl:1.17.3
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
