apiVersion: v1
kind: Pod
metadata:
  name: ci-nodejs-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: nodejs
      image: node:14.4-alpine
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
