apiVersion: v1
kind: Pod
metadata:
  name: ci-nodejs-slave
  namespace: jenkinsci
spec:
  serviceAccount: jenkinsci-slave-serviceaccount
  podRetention: never()
  containers:
    - name: nodejs
      image: node:13.8.0-alpine
      command:
        - cat
      tty: true
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
